"""added genres column to venue table

Revision ID: 539ad7561b1b
Revises: 48fd91c530be
Create Date: 2020-05-02 14:52:40.190762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539ad7561b1b'
down_revision = '48fd91c530be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
