"""added primary key to Shows table

Revision ID: a33027030924
Revises: 3ca4647681e1
Create Date: 2020-04-05 20:02:10.144431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33027030924'
down_revision = '3ca4647681e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'id')
    # ### end Alembic commands ###
